apiVersion: v1
kind: Secret
metadata:
  name: {{ include "seventh-ai-vision.fullname" . }}-secret
  labels:
    {{- include "seventh-ai-vision.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "seventh-ai-vision.databaseUrl" . | quote }}
  POSTGRES_HOST: {{ if .Values.postgres.enabled }}{{ include "seventh-ai-vision.fullname" . }}-postgres{{ else }}""{{ end }}
  POSTGRES_USER: {{ .Values.postgres.superuserUsername | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.superuserPassword | quote }}
  POSTGRES_DB: {{ .Values.postgres.database | quote }}
  JWT_SECRET_KEY_CURRENT: {{ .Values.secrets.jwtSecretKeyCurrent | quote }}
  JWT_SECRET_KEY_PREVIOUS: {{ .Values.secrets.jwtSecretKeyPrevious | quote }}
  SMTP_PASSWORD: {{ .Values.secrets.smtpPassword | quote }}
  TWILIO_ACCOUNT_SID: {{ .Values.secrets.twilioAccountSid | quote }}
  TWILIO_AUTH_TOKEN: {{ .Values.secrets.twilioAuthToken | quote }}
  S3_ACCESS_KEY: {{ if .Values.minio.enabled }}{{ .Values.minio.accessKey | quote }}{{ else }}""{{ end }}
  S3_SECRET_KEY: {{ if .Values.minio.enabled }}{{ .Values.minio.secretKey | quote }}{{ else }}""{{ end }}
